version: '3.8'
services:
  blog-service:
    image: pengliuyi/blog-ms:latest
    container_name: blog
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/b?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_JPA_HIBERNATE_DDL-AUTO: update
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
#      SERVER_PORT: 8081 # Not sure
#      TZ: Asia/Tokyo # Change all the time zone to your own

    depends_on:
      - db
      - service-registry
      - config-server
    networks:
      - microservice-network
    volumes:
      - ./images:/images

  db:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_DATABASE: b
      MYSQL_ROOT_PASSWORD: root
#      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - microservice-network

  config-server:
    image: pengliuyi/config-server-ms:latest
    container_name: config-server
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker # application-docker.yml will be picked up

  service-registry:
    image: pengliuyi/service-reg-ms:latest
    container_name: service-registry
    ports:
      - "8761:8761"
#    depends_on:
#      - rabbitmq
#      - zipkin
#      - db
    networks:
      - microservice-network

  comment-service:
    image: pengliuyi/comment-ms:latest
    container_name: comment
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-network

  gateway:
    image: pengliuyi/gateway-ms:latest
    container_name: gateway
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservice-network
volumes:
  mysql-data:

networks:
    microservice-network:
      driver: bridge